### ISSUE TITLE
Unable to publish posts that never expire

### ISSUE THREAD

**Issue by qurbat** [i5hi/cypherpost#15]
![Image](https://i.imgur.com/ZaGUL3X.png)

As the title describes, any post with the expiry timer set to 'Never' does not get published, even though the HTTP request returns a `200`. Further, this action seems to delete all previous posts made by a particular user - or at the very least makes any previous posts not appear in the UI.

**Comment by qurbat** [comment]
I suspect this has something to do with the `expiry` parameter for posts that aren't intended to expire being `0`, though I am not fully sure.

**Comment by i5hi** [comment]
I send expiry as value 0 for never expiring posts AND when fetching posts delete all posts with expiry < Date.now(). 

Fixed this.

**Comment by i5hi** [comment]
Found some more bugs in dealing with expired posts. Also need to delete the expired post's key from each of the trusting user's key store.

**Comment by i5hi** [comment]
Will also need a db migration script now to delete keys from users profile for all the posts that have expired to date.
