### ISSUE TITLE
Visibility feature for posts

### ISSUE THREAD

**Issue by i5hi** [i5hi/cypherpost#23]
Based on visibility, update eveyones post_keys.

**Comment by RaviPatelGit** [comment]
In current version, my post and contact info is visible to only people I trust.

These should be the options to choose for visibility, while creating a post/updating contact info:
1. only visible to people I trust
2. only visible to people I trust and people they trust.

**Comment by i5hi** [comment]
Fully client side update.

**Comment by i5hi** [comment]
Actually, server should only store the Visibility type, so when the client gets a post from server, it knows how to update visibility incase client revokes trust in someone - it will have to recalculate new post keys.

**Comment by i5hi** [comment]
Not required.

Client handpicks identities that can view profile and posts. 

They can use badges to help them pick, or just pick 1 or 2 identities per post.
